alias: Set bathroom volumio volume when cube rotate
trigger:
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_bathroom1
      action_type: rotate
condition:
  - condition: state
    entity_id: 'media_player.bathroom_volumio'
    state: 'playing'     
action:
    - service: media_player.volume_set
      entity_id: media_player.bathroom_volumio
      data_template:
        volume_level: '
        {%if trigger.event.data.action_value | float > 0 and states.media_player.bathroom_volumio.attributes.volume_level | float <= 0.9 %} 
          {{ states.media_player.bathroom_volumio.attributes.volume_level | float + 0.1}}
        {% elif trigger.event.data.action_value | float < 0 and states.media_player.bathroom_volumio.attributes.volume_level | float >= 0.1 %}
          {{ states.media_player.bathroom_volumio.attributes.volume_level | float - 0.1}}
        {% elif trigger.event.data.action_value | float > 0 and states.media_player.bathroom_volumio.attributes.volume_level | float > 0.9 %}
          1.0
        {% elif trigger.event.data.action_value | float < 0 and states.media_player.bathroom_volumio.attributes.volume_level | float < 0.1 %}
          0.0
        {% else %} 
          0.3
        {% endif %}'
