  alias: Turn on lamp in living room
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_living_room_1
      click_type: single
  action:
    - service: homeassistant.turn_on
      entity_id: switch.living_room
