alias: Turn off small light when cube flip 90
trigger:
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_living_room_1
      action_type: flip90
condition:
  - condition: state
    entity_id: 'light.salon'
    state: 'on'    
action:
    - service: light.turn_off
      entity_id: light.salon