  alias: Good night
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_user1
      click_type: hold
  action:
    service: scene.turn_on
    entity_id: scene.good_night
