  alias: Trigger alarm while armed away
  trigger:
    - platform: state
      # Entry - door
      entity_id: binary_sensor.door_window_sensor_entry
      to: 'on'
    - platform: state
      # Entry - motion
      entity_id: binary_sensor.motion_sensor_entry
      to: 'on'      
    - platform: state
      # Living room - motion
      entity_id: binary_sensor.motion_sensor_living_room
      to: 'on'   
    - platform: state
      # Kitchen - window
      entity_id: binary_sensor.door_window_sensor_kitchen
      to: 'on'   
    - platform: state
      # Bedroom - motion
      entity_id: binary_sensor.motion_sensor_bedroom
      to: 'on'   
    - platform: state
      # Bedroom - left window
      entity_id: binary_sensor.door_window_sensor_bedroom_left
      to: 'on'
    - platform: state
      # Bedroom - right window
      entity_id: binary_sensor.door_window_sensor_bedroom_right
      to: 'on'
    - platform: state
      # Bathroom - motion
      entity_id: binary_sensor.motion_sensor_bathroom
      to: 'on'         
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - delay: '00:00:05'  
    - service: media_player.volume_set
      entity_id: media_player.kitchen_volumio
      data:
        volume_level: 0.7  
    - service: tts.google_say
      entity_id: media_player.volumio_mpd
      data_template:
        message: 'Witaj w domu'
        language: 'pl'  
    - delay: '00:00:07'
    - service: media_player.volume_set
      entity_id: media_player.kitchen_volumio
      data:
        volume_level: 0.2    
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm