   alias: User1 leave work
   trigger:
     platform: zone
     event: leave
     zone: zone.praca__user1
     entity_id: device_tracker.google_maps_user1
   action:
    - service: notify.defaultPushOver
      data:
        message: 'User1 wyszedł z pracy'