   alias: User2 leave home
   trigger:
     platform: zone
     event: leave
     zone: zone.dom
     entity_id: device_tracker.google_maps_user2
   action:
    - service: notify.defaultPushOver
      data:
        message: 'User2 wyszła z mieszkania'