   alias: User1 leave home
   trigger:
     platform: zone
     event: leave
     zone: zone.dom
     entity_id: device_tracker.google_maps_user1
   action:
    - service: notify.defaultPushOver
      data:
        message: 'User1 wyszedł z mieszkania'