  alias: Send weekend morning air quality information
  trigger:
    - platform: time
      at: '09:15:00'
  condition:
    - condition: time
    # At least one of the following is required.
      weekday:
       - sat
       - sun 
    - condition: state
    # User1 wifi
      entity_id: 'device_tracker.user1'
      state: 'home'       
  action:
    - service: notify.defaultPushOver
      data:
        message: '{{ states.sensor.airly_index_description.state }}
        
        {{ states.sensor.airly_index_advice.state }}

        PM 2.5 
        
          Zewnątrz: {{ states.sensor.airly_pm25.state }} μg/m3 - ({{ (states.sensor.airly_pm25.state | float / states.sensor.pm25_max_level.state | float * 100) | round(0) }}%)
        
          Wewnątrz: {{ states.sensor.air_quality_indoor_pm25.state }} μg/m3 - ({{ (states.sensor.air_quality_indoor_pm25.state | float / states.sensor.pm25_max_level.state | float * 100) | round(0) }}%)

        PM 10
        
          Zewnątrz: {{ states.sensor.airly_pm10.state }} μg/m3 - ({{ (states.sensor.airly_pm10.state | float / states.sensor.pm10_max_level.state | float * 100) | round(0) }}%)
        
          Wewnątrz: {{ states.sensor.air_quality_indoor_pm10.state }} μg/m3 - ({{ (states.sensor.air_quality_indoor_pm10.state | float / states.sensor.pm10_max_level.state | float * 100) | round(0) }}%)'