  - platform: google_maps
    username: !secret google_maps_username
    password: !secret google_maps_password
  - platform: nmap_tracker
    hosts: !secret nmap_tracker_hosts
    home_interval: !secret nmap_tracker_home_interval