#Groups
  Security:
    name: Alarm
    entities:
      - alarm_control_panel.home_alarm
      
  Temperature:
    name: Temperatura
    entities:
    - sensor.temperature_hall_1
    - sensor.temperature_bathroom_1
    - sensor.temperature_living_room_1
    
  Humidity:
    name: Wilgotność
    entities:
    - sensor.humidity_bathroom_1
    - sensor.humidity_hall_1
    - sensor.humidity_living_room_1  
    
  Doors:
    name: Drzwi
    entities:
    - binary_sensor.door_window_sensor_entry

  Windows:
    name: Okna
    entities:
    - binary_sensor.door_window_sensor_balcony
    - binary_sensor.door_window_sensor_kitchen
    - binary_sensor.door_window_sensor_living_room     
      
  MotionSensors:
    name: Ruch
    entities:
    - binary_sensor.motion_sensor_living_room
    - binary_sensor.motion_sensor_hall
      
  Lights:
    name: Oświetlenie
    entities:
    - switch.living_room
    
  Illuminations:
    name: Jasność
    entities:
    - sensor.illumination_gateway_living_room
    - sensor.illumination_hall

  MediaPlayers:
    name: Odtwarzacze
    entities:
    - media_player.living_room_tv
    - media_player.living_room_volumio
    - media_player.volumio_mpd

  WeatherToday:
    name: Dzisiaj
    entities:
    - sensor.dark_sky_summary
    - sensor.dark_sky_temperature
    - sensor.dark_sky_daytime_high_temperature_0
    - sensor.dark_sky_overnight_low_temperature_0
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_humidity
    - sensor.dark_sky_pressure
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_cloud_coverage
    
  WeatherForecastTomorrow:
    name: Jutro
    entities:
    - sensor.dark_sky_summary_1
    - sensor.dark_sky_daytime_high_temperature_1
    - sensor.dark_sky_overnight_low_temperature_1
    - sensor.dark_sky_humidity_1
    - sensor.dark_sky_pressure_1
    - sensor.dark_sky_wind_speed_1
    
  WeatherPrecipitationForecastTomorrow:
    name: Opady jutro
    entities:
    - sensor.dark_sky_precip_1
    - sensor.dark_sky_precip_probability_1
    - sensor.dark_sky_precip_intensity_1

    
  AirQuality:
    name: Powietrze
    entities:
    - sensor.airly_pm25
    - sensor.air_quality_indoor_pm25
    - sensor.airly_pm10
    - sensor.air_quality_indoor_pm10    
    - sensor.airly_index_description
    - sensor.airly_index_advice

  System:
    name: System
    entities:
    - sensor.processor_use
    - sensor.load_1m
    - sensor.memory_use_percent
    - sensor.disk_use_percent
    - sensor.last_boot
    - sensor.network_out_eth0
    - sensor.network_in_eth0

#Tabs
  default_view:
    name: Ogólne
    view: yes
    entities:
    - group.security
    - group.temperature
    - group.humidity
    - group.motionsensors
    - group.doors
    - group.windows
    - group.illuminations
    - group.lights
    - updater.updater
    - sensor.hass_update_available

  MediaView:
    name: Multimedia
    view: yes
    entities:
    - group.mediaplayers
    
  WeatherView:
    name: Pogoda
    view: yes
    entities:
    - group.airquality
    - group.weathertoday
    - group.weatherprecipitationforecasttomorrow
    - group.weatherforecasttomorrow

  SystemView:
    name: System
    view: yes
    entities:
    - group.system