  - platform: samsungtv
    name: Living Room TV
    host: !secret living_room_samsungtv_ip
    port: !secret living_room_samsungtv_port
    timeout: !secret living_room_samsungtv_timeout
  - platform: volumio
    name: Kitchen Room Volumio
    host: !secret kitchen_volumio_ip
    port: !secret kitchen_volumio_port
  - platform: mpd
    name: volumio_mpd
    host: !secret kitchen_volumio_mdp_ip