  - platform: samsungtv
    name: Living Room TV
    host: !secret living_room_samsungtv_ip
    port: !secret living_room_samsungtv_port
    timeout: !secret living_room_samsungtv_timeout
  - platform: volumio
    name: Kitchen Room Volumio
    host: !secret kitchen_volumio_ip
    port: !secret kitchen_volumio_port
  - platform: mpd
    name: volumio_mpd
    host: !secret kitchen_volumio_mdp_ip
  - platform: volumio
    name: Bathroom volumio
    host: !secret bathroom_volumio_ip
    port: !secret bathroom_volumio_port
  - platform: mpd
    name: bathroom_volumio_mpd
    host: !secret bathroom_volumio_mdp_ip
  - platform: androidtv
    name: Sypialnia TV
    host: !secret bedroom_tv_ip
    adb_server_ip: !secret adb_server_ip
    adb_server_port: !secret adb_server_port            