  - name: defaultPushOver
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_api_user_key_mimax

  - name: messenger
    platform: facebook
    page_access_token: !secret messenger_page_access_token