http_base_url:
# Pushover
pushover_api_key:
pushover_api_user_key_mimax:
# Home settings
latitude: 
longitude: 
elevation: 
time_zone: 
# Zones
#   user1
work_user1_latitude: 
work_user1_longitude: 
#   user2
work_user2_latitude: 
work_user2_longitude: 
#   home
work_home_latitude: 
work_home_longitude: 
# Xiaomi gateway
xiaomi_aqara_key: 
# Alarm
alarm_key: 
# Messenger
messenger_page_access_token:
# Darksky
darksky_api_key:
# Media players
#   living room samsung TV
living_room_samsungtv_ip: 
living_room_samsungtv_port: 
living_room_samsungtv_timeout: 
#   living room volumio
kitchen_volumio_ip: 
kitchen_volumio_port: 
kitchen_volumio_mdp_ip:
#   bathroom volumio
bathroom_volumio_ip:
bathroom_volumio_port:
bathroom_volumio_mdp_ip:
#   bedroom TV
bedroom_tv_ip:
# Adb server
adb_server_ip:
adb_server_port:
# Nmap tracker
nmap_tracker_hosts:
nmap_tracker_home_interval: