  alias: Morning play music
  trigger:
    - platform: time
      at: '06:16:00'
  condition:
    - condition: time
    # At least one of the following is required.
      weekday:
       - mon
       - tue
       - wed
       - thu
       - fri   
    - condition: state
    # User1 wifi
      entity_id: 'device_tracker.user1'
      state: 'home'       
  action:
    - service: media_player.volume_set
      entity_id: media_player.kitchen_volumio
      data:
        volume_level: 0.1      
    - service: media_player.media_play
      entity_id: media_player.kitchen_volumio
    - delay:
          minutes: 1
    - service: media_player.volume_set
      entity_id: media_player.kitchen_volumio
      data:
        volume_level: 0.15
    - delay:
          minutes: 1
    - service: media_player.volume_set
      entity_id: media_player.kitchen_volumio
      data:
        volume_level: 0.2          
    - delay:
          minutes: 1
    - service: media_player.volume_set
      entity_id: media_player.kitchen_volumio
      data:
        volume_level: 0.25